[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 10

[font.bold]
family = "CommitMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "CommitMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "CommitMonoNerdFont"
style = "Italic"

[font.normal]
family = "CommitMonoNerdFont"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 1
y = 0

